//
//  SimpleLineIcon.swift
//  SimpleLineIcons
//
//  Created by Dairon Ian Garcia Roque on 19/1/26.
//

public enum SimpleLineIcon: String, CaseIterable {
    case simple_icon_space = "uni0020"
    case simple_icon_user_female = "uniE000"
    case simple_icon_people = "uniE001"
    case simple_icon_user_follow = "uniE002"
    case simple_icon_user_following = "uniE003"
    case simple_icon_user_unfollow = "uniE004"
    case simple_icon_user = "uniE005"
    case simple_icon_trophy = "uniE006"
    case simple_icon_speedometer = "uniE007"
    case simple_icon_social_youtube = "uniE008"
    case simple_icon_social_twitter = "uniE009"
    case simple_icon_social_tumblr = "uniE00A"
    case simple_icon_social_facebook = "uniE00B"
    case simple_icon_social_dropbox = "uniE00C"
    case simple_icon_social_dribbble = "uniE00D"
    case simple_icon_shield = "uniE00E"
    case simple_icon_screen_tablet = "uniE00F"
    case simple_icon_screen_smartphone = "uniE010"
    case simple_icon_screen_desktop = "uniE011"
    case simple_icon_plane = "uniE012"
    case simple_icon_notebook = "uniE013"
    case simple_icon_mustache = "uniE014"
    case simple_icon_mouse = "uniE015"
    case simple_icon_magnet = "uniE016"
    case simple_icon_magic_wand = "uniE017"
    case simple_icon_hourglass = "uniE018"
    case simple_icon_graduation = "uniE019"
    case simple_icon_ghost = "uniE01A"
    case simple_icon_game_controller = "uniE01B"
    case simple_icon_fire = "uniE01C"
    case simple_icon_eyeglass = "uniE01D"
    case simple_icon_envelope_open = "uniE01E"
    case simple_icon_envolope_letter = "uniE01F"
    case simple_icon_energy = "uniE020"
    case simple_icon_emotsmile = "uniE021"
    case simple_icon_disc = "uniE022"
    case simple_icon_cursor_move = "uniE023"
    case simple_icon_crop = "uniE024"
    case simple_icon_credit_card = "uniE025"
    case simple_icon_chemistry = "uniE026"
    case simple_icon_bell = "uniE027"
    case simple_icon_badge = "uniE028"
    case simple_icon_anchor = "uniE029"
    case simple_icon_wallet = "uniE02A"
    case simple_icon_vector = "uniE02B"
    case simple_icon_speech = "uniE02C"
    case simple_icon_puzzle = "uniE02D"
    case simple_icon_printer = "uniE02E"
    case simple_icon_present = "uniE02F"
    case simple_icon_playlist = "uniE030"
    case simple_icon_pin = "uniE031"
    case simple_icon_picture = "uniE032"
    case simple_icon_map = "uniE033"
    case simple_icon_layers = "uniE034"
    case simple_icon_handbag = "uniE035"
    case simple_icon_globe_alt = "uniE036"
    case simple_icon_globe = "uniE037"
    case simple_icon_frame = "uniE038"
    case simple_icon_folder_alt = "uniE039"
    case simple_icon_film = "uniE03A"
    case simple_icon_feed = "uniE03B"
    case simple_icon_earphones_alt = "uniE03C"
    case simple_icon_earphones = "uniE03D"
    case simple_icon_drop = "uniE03E"
    case simple_icon_drawar = "uniE03F"
    case simple_icon_docs = "uniE040"
    case simple_icon_directions = "uniE041"
    case simple_icon_direction = "uniE042"
    case simple_icon_diamond = "uniE043"
    case simple_icon_cup = "uniE044"
    case simple_icon_compass = "uniE045"
    case simple_icon_call_out = "uniE046"
    case simple_icon_call_in = "uniE047"
    case simple_icon_call_end = "uniE048"
    case simple_icon_calculator = "uniE049"
    case simple_icon_bubbles = "uniE04A"
    case simple_icon_briefcase = "uniE04B"
    case simple_icon_book_open = "uniE04C"
    case simple_icon_basket_oaded = "uniE04D"
    case simple_icon_basket = "uniE04E"
    case simple_icon_bag = "uniE04F"
    case simple_icon_action_undo = "uniE050"
    case simple_icon_action_redo = "uniE051"
    case simple_icon_wrench = "uniE052"
    case simple_icon_umbrella = "uniE053"
    case simple_icon_trash = "uniE054"
    case simple_icon_tag = "uniE055"
    case simple_icon_support = "uniE056"
    case simple_icon_size_fullscreen = "uniE057"
    case simple_icon_size_actual = "uniE058"
    case simple_icon_shuffle = "uniE059"
    case simple_icon_share_alt = "uniE05A"
    case simple_icon_share = "uniE05B"
    case simple_icon_rocket = "uniE05C"
    case simple_icon_question = "uniE05D"
    case simple_icon_pie_chart = "uniE05E"
    case simple_icon_pencil = "uniE05F"
    case simple_icon_note = "uniE060"
    case simple_icon_music_tone_alt = "uniE061"
    case simple_icon_music_tone = "uniE062"
    case simple_icon_microphone = "uniE063"
    case simple_icon_loop = "uniE064"
    case simple_icon_logout = "uniE065"
    case simple_icon_login = "uniE066"
    case simple_icon_list = "uniE067"
    case simple_icon_like = "uniE068"
    case simple_icon_home = "uniE069"
    case simple_icon_grid = "uniE06A"
    case simple_icon_graph = "uniE06B"
    case simple_icon_equalizer = "uniE06C"
    case simple_icon_dislike = "uniE06D"
    case simple_icon_cursor = "uniE06E"
    case simple_icon_control_start = "uniE06F"
    case simple_icon_control_rewind = "uniE070"
    case simple_icon_control_play = "uniE071"
    case simple_icon_control_pause = "uniE072"
    case simple_icon_control_forward = "uniE073"
    case simple_icon_control_end = "uniE074"
    case simple_icon_calender = "uniE075"
    case simple_icon_bulb = "uniE076"
    case simple_icon_chart = "uniE077"
    case simple_icon_arrow_up_circle = "uniE078"
    case simple_icon_arrow_right_circle = "uniE079"
    case simple_icon_arrow_left_circle = "uniE07A"
    case simple_icon_arrow_down_circle = "uniE07B"
    case simple_icon_ban = "uniE07C"
    case simple_icon_bubble = "uniE07D"
    case simple_icon_camrecorder = "uniE07E"
    case simple_icon_camera = "uniE07F"
    case simple_icon_check = "uniE080"
    case simple_icon_clock = "uniE081"
    case simple_icon_close = "uniE082"
    case simple_icon_cloud_download = "uniE083"
    case simple_icon_cloud_upload = "uniE084"
    case simple_icon_doc = "uniE085"
    case simple_icon_envolope = "uniE086"
    case simple_icon_eye = "uniE087"
    case simple_icon_flag = "uniE088"
    case simple_icon_folder = "uniE089"
    case simple_icon_heart = "uniE08A"
    case simple_icon_info = "uniE08B"
    case simple_icon_key = "uniE08C"
    case simple_icon_link = "uniE08D"
    case simple_icon_lock = "uniE08E"
    case simple_icon_lock_open = "uniE08F"
    case simple_icon_magnifier = "uniE090"
    case simple_icon_magnifier_add = "uniE091"
    case simple_icon_magnifier_remove = "uniE092"
    case simple_icon_paper_clip = "uniE093"
    case simple_icon_paper_plane = "uniE094"
    case simple_icon_plus = "uniE095"
    case simple_icon_location_pin = "uniE096"
    case simple_icon_power = "uniE097"
    case simple_icon_refresh = "uniE098"
    case simple_icon_reload = "uniE099"
    case simple_icon_settings = "uniE09A"
    case simple_icon_star = "uniE09B"
    case simple_icon_symble_female = "uniE09C"
    case simple_icon_symbol_male = "uniE09D"
    case simple_icon_target = "uniE09E"
    case simple_icon_volume_1 = "uniE09F"
    case simple_icon_volume_2 = "uniE0A0"
    case simple_icon_volume_off = "uniE0A1"
    case simple_icon_phone = "uniE600"
    case simple_icon_menu = "uniE601"
    case simple_icon_options_vertical = "uniE602"
    case simple_icon_options = "uniE603"
    case simple_icon_arrow_down = "uniE604"
    case simple_icon_arrow_left = "uniE605"
    case simple_icon_arrow_right = "uniE606"
    case simple_icon_arrow_up = "uniE607"
    case simple_icon_paypal = "uniE608"
    case simple_icon_social_instagram = "uniE609"
    case simple_icon_social_linkedin = "uniE60A"
    case simple_icon_social_pintarest = "uniE60B"
    case simple_icon_social_github = "uniE60C"
    case simple_icon_social_google = "uniE60D"
    case simple_icon_social_reddit = "uniE60E"
    case simple_icon_social_skype = "uniE60F"
    case simple_icon_social_behance = "uniE610"
    case simple_icon_social_foursqare = "uniE611"
    case simple_icon_social_soundcloud = "uniE612"
    case simple_icon_social_spotify = "uniE613"
    case simple_icon_social_stumbleupon = "uniE614"
    case simple_icon_minus = "uniE615"
    case simple_icon_organization = "uniE616"
    case simple_icon_exclamation = "uniE617"
    case simple_icon_social_vkontakte = "uniE618"
    case simple_icon_event = "uniE619"
    case simple_icon_social_steam = "uniE620"
}

public extension SimpleLineIcon {

    /// Convierte "simple-icon-layers" (API) a `.simple_icon_layers`
    init?(name: String) {
        // "simple-icon-layers" -> "simple_icon_layers"
        let normalized = name
            .replacingOccurrences(of: "-", with: "_")

        self.init(caseInsensitiveRawCaseName: normalized)
    }

    /// Devuelve el carácter Unicode real del icono
    var unicodeScalar: String {
        let hex = rawValue
            .replacingOccurrences(of: "uni", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        guard let value = UInt32(hex, radix: 16),
              let scalar = UnicodeScalar(value) else {
            return ""
        }
        return String(scalar)
    }

    /// Helper: inicializa por nombre del case (no por rawValue)
    private init?(caseInsensitiveRawCaseName name: String) {
        // Compara con el nombre del case (String(describing:))
        if let match = Self.allCases.first(where: { String(describing: $0).lowercased() == name.lowercased() }) {
            self = match
            return
        }
        return nil
    }
}

